### ISSUE TITLE
IOError: mkdir: no such file or directory (ENOENT)

### ISSUE THREAD

**Issue by SodzieR** [compbiocore/VariantVisualization.jl#102]
I have checked node.js, npm so far and I think WebIO as well. Moved the directory and files a few times and made a fresh install of Julia. Still the same thing: IOError: mkdir: no such file or directory (ENOENT).

**Comment by gtollefson** [comment]
Hi @SodzieR ,

Thank you for bringing this issue up. Let's get this solved! Can you paste the complete julia command that you ran and the entire stacktrace? It seems like the working directory doesn't exist. When you are in the Julia REPL, what do you get when you run:

julia> filesize("YOUR_VCF_FILENAME_WITH_PATH")

Thank you,
George

**Comment by SodzieR** [comment]
I got it working eventually on Ubuntu.

Anyway thank you :)
