### ISSUE TITLE
Error building VariantVisualization

### ISSUE THREAD

**Issue by dridk** [compbiocore/VariantVisualization.jl#80]
I get the following error when installing on Linux ubuntu 18.04 

```
Building VariantVisualization → `~/.julia/packages/VariantVisualization/1yoNl/deps/build.log`
┌ Error: Error building `VariantVisualization`: 
│ ERROR: LoadError: IOError: symlink: permission denied (EACCES)
│ Stacktrace:
│  [1] uv_error at ./libuv.jl:90 [inlined]
│  [2] symlink(::String, ::String) at ./file.jl:800
│  [3] symlink_user_bin(::String) at /home/sacha/.julia/packages/VariantVisualization/1yoNl/deps/build.jl:18
│  [4] top-level scope at /home/sacha/.julia/packages/VariantVisualization/1yoNl/deps/build.jl:24
│  [5] include at ./boot.jl:328 [inlined]
│  [6] include_relative(::Module, ::String) at ./loading.jl:1094
│  [7] include(::Module, ::String) at ./Base.jl:31
│  [8] include(::String) at ./client.jl:431
│  [9] top-level scope at none:5
│ in expression starting at /home/sacha/.julia/packages/VariantVisualization/1yoNl/deps/build.jl:24
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Pkg/src/backwards_compatible_isolation.jl:647
```

**Comment by gtollefson** [comment]
Hi @dridk, it looks like there is a permissions error resulting from VIVA’s script to create a symbolic link on your Linux system. Are you installing on a remote server and do you have permission to create symlinks on that server?

**Comment by dridk** [comment]
I fixed it by creating the symlink myself. 
By the way, the simple commande `viva -help` takes some time before showing useful things. It loads many thinks before. Is it normal ?

**Comment by gtollefson** [comment]
@dridk Great! I'm glad that worked. It should take about 20-30 seconds for the Julia dependency packages to load before the `-help` parameter is interpreted. I'm sorry if that's inconvenient - that is something we'll be addressing in a future release.
