### ISSUE TITLE
How to install viva in hpc

### ISSUE THREAD

**Issue by Kalpi-ds** [compbiocore/VariantVisualization.jl#81]
Hi,

I have  julia-0.3.6-generic in hpc. I want to know how I can install viva in my hpc account.
My vcf file is very large so I can not download it to my computer. I am new to bioinformatics analysis and this tools seems it can ease my life. Your help is much appreciated.

**Comment by gtollefson** [comment]
Hi @Kalpi-ds, thanks for your interest in VIVA! Let's get it set up together.

You want to install VIVA on a remote high performance computing environment. First, you will have to ask the admins of your HPC system install the newest version of Julia. Any version after version 1.0 will work. 

Once Julia v1.+ is installed, you can install the VariantVisualization.jl package following the [installation documentation](https://compbiocore.github.io/VariantVisualization.jl/latest/installation/). Installing VIVA on remote servers can be tricky, so we may need to work together to install it. Please let me know if you run into any errors during the installation.

**Comment by Kalpi-ds** [comment]
Thank you @gtollefson. I tried to get VIVA run on Jupyter notebook in my desktop while they install it on hpc. I followed instructions here https://github.com/compbiocore/VariantVisualization.jl/blob/master/VIVA.ipynb
and ran into following errors.

Welcome to VIVA Jupyter Notebook.

Loading packages:

1/5 ArgParse
2/5 VariantVisualization

┌ Info: Recompiling stale cache file C:\Users\Kalpani\.julia\compiled\v1.2\VariantVisualization\v8cR2.ji for VariantVisualization [7f8bf45c-0ad5-53b5-97e6-33c1305e0aa4]
└ @ Base loading.jl:1240
WARNING: using HTTP.stack in module Mux conflicts with an existing identifier.

Unable to load WebIO. Please make sure WebIO works for your Jupyter client. For troubleshooting, please see the WebIO/IJulia documentation. 

3/5 PlotlyJS
4/5 GeneticVariation
5/5 DelimitedFiles
Out[7]:
("", "html", "", "", "true")
In [8]:


jupyter_main(vcf_filename,saving_options,variant_filters,sample_selection,plotting_options)
;



Reading /Users/Kalpani/.julia/packages/VariantVisualization/1yoNl/test/test_files/test_4X_191.vcf


SystemError (with ): mkdir: No such file or directory

Stacktrace:
 [1] #systemerror#44(::String, ::typeof(systemerror), ::Symbol, ::Bool) at .\error.jl:134
 [2] #systemerror at .\none:0 [inlined]
 [3] #mkdir#7(::UInt16, ::typeof(mkdir), ::String) at .\file.jl:167
 [4] mkdir at .\file.jl:162 [inlined]
 [5] checkfor_outputdirectory at C:\Users\Kalpani\.julia\packages\VariantVisualization\1yoNl\src\vcf_utils_complete.jl:1071 [inlined]
 [6] jupyter_main(::String, ::NTuple{5,String}, ::Tuple{String,String,String}, ::Tuple{Tuple{String,String},String}, ::NTuple{4,String}) at C:\Users\Kalpani\.julia\packages\VariantVisualization\1yoNl\src\new_notebook_utils.jl:35
 [7] top-level scope at In[8]:1

In [ ]:

I got the following message when I tried to install WebIO using Julia.

julia> Pkg.build("WebIO")
  Building MbedTLS → `C:\Users\Kalpani\.julia\packages\MbedTLS\a1JFn\deps\build.log`
  Building WebIO ──→ `C:\Users\Kalpani\.julia\packages\WebIO\2mZPb\deps\build.log`
false
​
Can you please help me in figuring out what I should do next.

Thank you

**Comment by gtollefson** [comment]
Hi @Kalpi-ds, sorry for the delay. What OS are you running on your desktop? Let's figure this out. Have you been able to run it yet?

If you want to run VIVA without troubleshooting installation, I'd recommend running via Docker. It should take care of any dependency issues. The instructions to run from Docker are [here](https://compbiocore.github.io/VariantVisualization.jl/latest/installation/#run-the-viva-command-line-tool-from-a-docker-image).

**Comment by gtollefson** [comment]
I'm closing this since it's been a year since our last reply. Please feel free to reopen it anytime @Kalpi-ds.
