### ISSUE TITLE
Cannot complete step 2 of installation

### ISSUE THREAD

**Issue by jasiozaucha** [compbiocore/VariantVisualization.jl#85]
Running the following from the julia command line:

```
]add VariantVisualization
exit()

```
Yields the following error:

> ERROR: syntax: unexpected "]"
> Stacktrace:
>  [1] top-level scope at none:0

**Comment by gtollefson** [comment]
@jasiozaucha Thanks for your question. What version of Julia are you using? Typing right bracket `]` in the REPL is just the command to enter the package manager. It should not throw this error as long as you are using Julia v1.0+. 

If you are using Julia v1.0+ and getting the error, I would try putting a space between `]` and `add`. Let me know if you are able to run it.

**Comment by jasiozaucha** [comment]
I was using Julia 1.2.
Its a bit crazy but the bracket copied from the website is different to the bracket I could successfully input using my keyboard. Some encoding issue I guess.

**Comment by gtollefson** [comment]
@jasiozaucha Ok, that makes sense. I'll add an extra space in the documentation example code to make it more clear. 

I'll close this issue now since we've resolved it. Please feel free to post another issue if you have any questions.

**Comment by gtollefson** [comment]
@jasiozaucha Ok, that makes sense. I'll add an extra space in the documentation example code to make it more clear. 

I'll close this issue now since we've resolved it. Please feel free to post another issue if you have any questions.

**Comment by evan-wehi** [comment]
I think you need to fix the installation instructions. I copied and pasted and had the same problem. By hitting the `]` separately it entered what I assume is package manager mode and I could then install the package. I don't how to get out of PM mode - ^D sent me back to the command prompt.

In my experience, julia is pretty much unheard of in bioinformatics so you should bear that in mind when writing documentation.

**Comment by vmkalbskopf** [comment]
Yup, I still have this issue when copy-pasting your instructions.
